name: hack_puzzle
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  awesome_dialog: ^2.1.2
  confetti: ^0.6.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  logger: ^1.1.0
  material_dialogs: ^1.1.1
  path: ^1.8.0
  sqflite: ^2.0.2
  stop_watch_timer: ^1.3.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/json/animations/
